import { readdir, mkdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
async function scan(dir) {
  const files = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.name === "optimized") continue;
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await scan(p)));
    else if (p.endsWith(".png")) files.push(p);
  }
  return files;
}
await mkdir("public/assets/optimized", { recursive: true });
const files = await scan("public/assets");
let original = 0,
  optimized = 0;
const catalog = {};
for (const file of files) {
  const name = path.basename(file, ".png"),
    size =
      name.includes("BG_") || name.includes("FRAME_")
        ? 1000
        : name.includes("AVATAR")
          ? 180
          : name.startsWith("GEM_")
            ? 144
            : 400;
  const output = `public/assets/optimized/${name}.webp`;
  await sharp(file)
    .resize(size, size, { fit: "inside", withoutEnlargement: true })
    .webp({ quality: 88 })
    .toFile(output);
  original += (await stat(file)).size;
  optimized += (await stat(output)).size;
  catalog[name] = {
    original: "/" + file.replaceAll("\\", "/").replace("public/", ""),
    url: "/" + output.replace("public/", ""),
  };
}
await writeFile(
  "src/data/assets/catalog.js",
  "// Generated by scripts/prepare-assets.js from the supplied production pack.\nexport const ASSET_CATALOG = " +
    JSON.stringify(catalog, null, 2) +
    ";\n",
);
const report = {
  count: files.length,
  originalBytes: original,
  optimizedBytes: optimized,
  missing: ["HERO_004_SYLVA_FULL_BODY.png"],
};
await writeFile(
  "public/assets/asset-audit.json",
  JSON.stringify(report, null, 2),
);
console.log(report);
