import "./styles/base.css";
import "./core/vfx/battle-vfx.css";
import { createGameRouter } from "./core/appRouter.js";
import { preloadStage } from "./data/assets/preloader.js";
import { installAssetFallbacks } from "./data/assets/manifest.js";
installAssetFallbacks(document.querySelector("#app"));
await preloadStage();
const router = createGameRouter(document.querySelector("#app"));
router.start();
if (import.meta.env.DEV) window.__gameRouter = router;
